version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/aws-test-next
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 600
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 1500