version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the Next.js app...
      - npm run build
      - echo Cleaning up to reduce bundle size...
      - rm -rf node_modules
      - rm -rf .git
      - rm -rf .next/cache
      - find . -name "*.log" -delete
      - find . -name "*.tmp" -delete
      - echo "Bundle size after cleanup"
      - du -sh .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: '.'
  exclude-paths:
    - 'node_modules/**/*'
    - '.git/**/*'
    - '.next/cache/**/*'
    - '*.log'
    - '*.tmp'
    - '.env*'
    - 'coverage/**/*'
    - 'tests/**/*'
    - '*.md'
    - '.gitignore'
    - '.eslintrc*'

